### ISSUE TITLE
Blocknumber on all entities by default

### ISSUE THREAD

**Issue by gorillatron** [zeitgeistpm/zeitgeist-subsquid#109]
In my humble opinion we should include block number of creation by default on all entities like Market, Pool etc.

The main reason for this is when we want to do some kind of aggregation/traversing on entities its good to know the lower bounds from when we need to traverse blocks for data.

**Comment by saboonikhil** [comment]
The following schemas show the real time data:
- Account
- AccountBalance
- Market
- Pool
- Asset

Most of the fields in the above schemas are static i.e, their values don't change.

The following historical schemas tracks the dynamic fields of the above schemas:
- HistoricalAccountBalance
- HistoricalMarket
- HistoricalPool
- HistoricalAsset

Technically, values at non-historical schemas are the resultant data derived from computation recorded at historical schemas.

Let's talk about the market, as soon as the new market is created, a new historicalMarket object with event `MarketCreated` and `marketId` would be created. This `marketId` can be referenced to derive the overall market data from `Market` schema. 

There are other ways of data traversal from time to time based on the use case.
