### ISSUE TITLE
Scalar market prediction in _Trending Markets_ doesn't match prediction in market view

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist-subsquid#192]
<img width="1920" alt="Screenshot 2022-09-24 at 21 29 28 1" src="https://user-images.githubusercontent.com/49552287/192115338-1f5aa816-2df6-4758-b3f4-d94dd2fb870f.png">

**Comment by saboonikhil** [comment]
Awaiting availability of rpc to pull spot prices without swap fees, so that both subsquid and ui are consistent on the topic (as discussed)

**Comment by saboonikhil** [comment]
This issue hasn't come up for quite some time. And looks resolved here (on one of the markets):

<img width="442" alt="Screenshot 2023-01-20 at 3 42 54 PM" src="https://user-images.githubusercontent.com/36529278/213670603-43a1ff39-8866-422f-9a6e-c388ca175a4b.png">
