### ISSUE TITLE
Stats aggregation/resolvers

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/zeitgeist-subsquid#214]
Implement a global stats schema either via resolvers or aggregation for overall stats.

The first stat is currently needed and blocking the new liquidity pools list from being released is total liquidity and volume for all pools.

**Suggesting something like:**
```gql
query stats {
  stats(where: {block: {_in [1,2,3,4]}, orderBy: block_DESC}) {
    totalLiquidity,
    totalTradedVolume
  }
}
```

_Being able to query for a set or range of blocks, and if the range of blocks is omitted it returns a singel stats item with the current latest values._

```gql
query stats {
  stats {
    totalLiquidity,
    totalTradedVolume
  }
}
```

Possible? ^^

**Comment by yornaath** [comment]
@numacoding This could probably be very useful and essential for developing the dashboard no?

**Comment by TvrtkoM** [comment]
I assume filtering by block numbers is so we can get market volume for a given period, but IMO would be better to be able to query directly by timestamp so client don't have to worry about converting time to block numbers>

e.g. having filter for `startTimestamp` and `endTimestamp` would be nice instead of `blocks` array

**Comment by yornaath** [comment]
I think filtering for a range/set of blocks **or** timestamps would be best since blocks is more precise while timestamps are more human friendly.

**Comment by saboonikhil** [comment]
How do you find this query for getting amount of assets in pool? I would recommend getting spot prices directly from chain initially for computing values. Long term solution would be getting rpc for swap price without swap fees (which Harald is going to add) and then setting up resolvers to compute real time values.
```
query AssetsInPool {
  accountBalances(where: {account: {poolId_eq: 29}}) {
    assetId
    balance
  }
}
```
Correlates with https://app.zeitgeist.pm/liquidity/29

**Comment by saboonikhil** [comment]
Subscriptions could be used for persisting data similar to _Trending Markets_. Since computing liquidity on each block/interval for all pools would be a very hard approach.

**Comment by saboonikhil** [comment]
And if you'd like to project the liquidity changes, you can use the below query (`accountId` can be retrieved from the above query) :
```
query LiquidityHistory {
  historicalAccountBalances(where: {accountId_eq: "dE1VdxVn8xy7HFNWfF1ZsAs12UzguijH3jKVH618bFYnWUZxc"}, orderBy: id_DESC) {
    assetId
    balance
    dBalance
    blockNumber
    event
  }
}
```

**Comment by saboonikhil** [comment]
<img width="621" alt="Screenshot 2024-01-29 at 6 30 08 PM" src="https://github.com/zeitgeistpm/zeitgeist-subsquid/assets/36529278/ee3b23a6-01e2-4dea-bbd1-c1b61ad9b6f9">
<img width="621" alt="Screenshot 2024-01-29 at 6 30 25 PM" src="https://github.com/zeitgeistpm/zeitgeist-subsquid/assets/36529278/b2063caf-ea12-45d3-b9ee-c792d09a36b1">
