### ISSUE TITLE
Historic prices seem broken

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist-subsquid#247]
I guess this is probably a subsquid issue related to on-chain arbitrage. We've talked about this before, but I noticed that there's no issue (I think). Just making sure this doesn't slip through the cracks.

<img width="1063" alt="Screenshot 2023-01-04 at 16 58 20" src="https://user-images.githubusercontent.com/49552287/210596298-94c9b00c-6650-4d78-8a88-42cfa521e250.png">

**Comment by saboonikhil** [comment]
Yes you're correct, it is because subsquid isn't tracking on-chain arbitrage.
