### ISSUE TITLE
Add package-lock.json to repository

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist-subsquid#26]
this file should be included in the repository

**Comment by saboonikhil** [comment]
After using `npm` and `yarn` as package management systems, I moved to `yarn` following its advantages locally and remotely. And in order to reduce maintenance of both `package-lock` and `yarn.lock` files: I have just kept the latter. 

In case there is an issue using `yarn`, do let me know.

**Comment by TvrtkoM** [comment]
personally didn't finda advantages in yarn over npm. bur whatever we need that lockfile (yarn or npm). tnx
