### ISSUE TITLE
MarketId is of type Float on PriceHistory

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#322]
Seems strange to use a float as an id, is this intentional?

<img width="535" alt="image" src="https://user-images.githubusercontent.com/4950844/224108958-23bf1c6d-79f6-41f4-8a73-1712523ae310.png">

**Comment by saboonikhil** [comment]
There are some synchronisation issues with the way custom resolvers are encoded and decoded by subsquid. This is the closest type I could get now for the `marketId` and I am sure this would improve as we go.
