### ISSUE TITLE
More detailed trade history

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#340]
We would like to display more information on trade history such as `assetIn`, `assetOut`, `assetInAmount`, `assetOutAmount`

@robhyrk

**Comment by saboonikhil** [comment]
> To add some more context:
> 
> We'd like to calculate the _total cost_ a user spends to acquire a particular asset per market on the portfolio page. We have information regarding the asset and the cost (value), however we are missing information to determine whether the user _bought_ or _sold_ an asset

If `dAmountInPool` is negative means user bought the asset, consequently `dPrice` would be positive. And vice versa when user sells the asset. However, there is an exception in the case of the event `PoolCreate` where both `dAmountInPool` and `dPrice` are positive (asset is initialised).

<img width="415" alt="Screenshot 2023-04-24 at 11 06 09 AM" src="https://user-images.githubusercontent.com/36529278/233908466-ef14edf1-fcbe-4e2a-a77e-73a2199a2143.png">

**Comment by Robiquet** [comment]
How are buys and sells defined?

**Comment by saboonikhil** [comment]
> How are buys and sells defined?

By looking for the `baseAsset` on the `assetIn`/`assetOut` args on the swap event. However, in case of swap between two outcome assets, the trade would be broken into fragments (which is yet to be implemented #212).

From the discussion we had today, I understand that UI wants to look at the `Swap` event as is and `historicalAsset` is massaged form of swap data which captures the asset price history along with user details.

On aligning the requirements with the current schema, I would like to highlight the two components which subsquid is segregated into: `archive` and `processor`. **Archive** just indexes the raw data as it looks on chain. Whereas **Processor** (built on top of archive) beautifies the existing data or helps create new schemas or modify existing for ease in extraction of information from the raw indexed data.

There are two different purposes which these two components are adhering to respectively. Currently, I am looking for the common ground which can meet UI requirements as well as put less load on processor.
