### ISSUE TITLE
Bonds "settled" property doesn't update

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#370]
The settled property should update when the bonds are returned:

```
query MyQuery {
  markets(orderBy: marketId_DESC, where: {status_eq: Resolved}) {
    creation
    bonds {
      creation {
        isSettled
        value
        who
      }
      oracle {
        isSettled
        value
        who
      }
    }
    marketId
    status
  }
}
```
Returns resolved markets where bonds aren't settled

**Comment by saboonikhil** [comment]
The bonds data post market creation need to be fetched via storage lookups. This might bump indexing speed, but worth an examination. 

What are the possible cases where bonds can be updated?

**Comment by Robiquet** [comment]
Advisory bond is settled when the market is approved. All other bonds settle when the market resolves
