### ISSUE TITLE
Compute volume in terms of dollar

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist-subsquid#380]
As trading volume is assessed based on movement of `baseAsset` through the pool. And with multi-assets being available as baseAsset, there's a need to normalise volumes for easy comparison.

For example: 100 DOT volume is worth like $500 dollars but 100ZTG volume is worth $6. When we sort them, the DOT market should be above the ZTG market.

Dollar seem to be commonly used fiat currency for all multi-assets.

**Comment by lsaether** [comment]
@saboonikhil Any update on this?
