### ISSUE TITLE
Accurately track ztg balances in sync with polkadot/apps

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist-subsquid#39]
I have picked up an user account with address `5DS9Sixa282b3mUY2BHUCT9RbSAM4Wkr35SZBobgx1xqLwkR` (or `dDzPbEaexFxtD7Ggm4DibCwm2swBWPkWVvYwdgvAipfBVNZzS`) for comparison of data shown via subsquid and polkadot/apps.

### Actual Outcome
After running the following query on [subsquid](https://processor.zeitgeist.pm/graphql) to view detailed ztg transfers -
```
query MyQuery {
  historicalAssetBalances(where: {account: {wallet_eq: "5DS9Sixa282b3mUY2BHUCT9RbSAM4Wkr35SZBobgx1xqLwkR"}, assetId_eq: "Ztg"}) {
    assetId
    amount
    blockNumber
    event
    balance
  }
}
```
We see that there are `14` transactions with initial balance as positive (meaning there wasn't any genesis balance) and final balance `27672801559`.

### Expected Outcome
After adding `dDzPbEaexFxtD7Ggm4DibCwm2swBWPkWVvYwdgvAipfBVNZzS` as contact in the address book via [polkadot/apps](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fbsr.zeitgeist.pm#/addresses) -

![image](https://user-images.githubusercontent.com/36529278/148040084-f710ed68-dffa-4a1a-8a80-0b79cba8f0e7.png)

We see that there are `13` transactions with final balance as `23756000000`.

.
.
.
.

Accounts with similar discrepancy:
- Pool account `5EYCAe5kj8FfBsJSCxzsebbMxA527Sb2WNjRcYeKxyCidyLf` (or `dE1VdxVn8xy7HFNWfF1Rzf6CyEf6BSgLgPrEW7fDMqcRNfU7q`)
- User account `5CzKnv3TyuipwdmNANs4f6LUnhnny8grP6AsDJHZsXRV4X4b` (or `dDywmamjrDkaT18ybCRJBfax65CoxJNSWGZfwiQrbkAe95wq3`)

Accounts which show accurate data:
- Pool account `5EYCAe5kj8FfBmwQJcE1nTXDApb57QBQiUQZY1i4MYNrumoo` (or `dE1VdxVn8xy7HFH9dLef8nx8pTKcESdw4bwue38H6EBbWwST6`)

**Comment by saboonikhil** [comment]
Update: Upon investigation, @sea212 and I discovered that there is [transaction fees](https://wiki.polkadot.network/docs/learn-transaction-fees) involved with each extrinsic. Initially it looks like this information is unavailable in the event. However, we are finding out ways to avoid [rpc call](https://polkadot.js.org/docs/substrate/rpc/#queryfeedetailsextrinsic-bytes-at-blockhash-feedetails) and ensure that the calculation is done while mapping in subsquid.

**Comment by sea212** [comment]
Some investigation into the runtime code was necessary to figure out how to determine the fees for an extrinsic. Here is a short summary of the required steps:

**Initialization**
Per Block. Those value can change at the initialization of each block through a runtime upgrade. The fee multiplier (2) can also change after each block AFAIK. Consequently the values for (1,3,4) can be stored after a runtime upgrade event was received, (2) should be fetched after each block.

1) Fetch and store extrinsic weight information: `const block_weights = api.consts.system.blockWeights`

2) Fetch and store fee multiplier: `const fee_multiplier = await api.query.transactionPayment.nextFeeMultiplier()`

3) Fetch and store weightToFee parameters: `const weight_to_fee = api.consts.transactionPayment.weightToFee`

4) Fetch and store transactionByteFee parameters: `const byte_fee = api.consts.transactionPayment.transactionByteFee`

**Fee calculation**
Per Extrinsic

For every `System.ExtrinsicSuccess` and `System.ExtrinsicFailure` event that has `paysFee = true`:

```js
// pseudocode
fee_per_byte = byte_fee * transaction_size_in_bytes
// weight from ExtrinsicSuccess/ExtrinsicFailure event
bounded_weight = min(weight, block_weights.maxBlock)
fee_unadjusted = conv_weight_to_fee(bounded_weight)
fee_adjusted = fee_multiplier * fee_unadjusted
// depends on class value in ExtrinsicSuccess/ExtrinsicFailure event:
bounded_base_weight = min(block_weights.perClass.normal/operational/mandatory.baseExtrinsic, block_weights.maxBlock)
base_fee = conv_weight_to_fee(bounded_base_weight)
total_fee = fee_per_byte + fee_adjusted + base_fee + transaction_tip // tip field is contained within extrinsic
// reduce account balance by total_fee

function conv_weight_to_fee(weight) {
    final = 0
    
    for wtf in weight_to_fee {
        w = weight ** wtf.degree
        frac = w * wtf.coeffFrac
        integer = w * wtf.coeffInteger
       
        if wtf.negative {
            final -= frac
            final -= integer
        } else {
            final += frac
            final += integer
        } 
    }
}
```

*Note: I am not sure if a balance event is thrown when a tip is included.*
*Note2: Ensure that all arithmetic operations are saturating.*

Further reads:
- [Transaction fees explanation](https://docs.substrate.io/v3/runtime/weights-and-fees/)
- [Calculate fee rust function](https://github.com/paritytech/substrate/blob/cfcdc10a0d37ba588b442332ab6f8153b358fa2b/frame/transaction-payment/src/lib.rs#L506-L546)
- [Weight to fee rust function](https://github.com/paritytech/substrate/blob/cfcdc10a0d37ba588b442332ab6f8153b358fa2b/frame/support/src/weights.rs#L673-L695)

**Comment by sea212** [comment]
Turns out that at some point the [balance pallet was updated to emit `Withdraw` events](https://github.com/paritytech/substrate/commit/12b6441ef138303f50fa2fb20895fbf57c8e4735#diff-7f35e750129ddf17862e61be2ce506a120ac7d4de151633d2c026525130bba7d) whenever a balance was withdrawn, for example to pay fees.

This change was added at `polkadot-v0.9.12`, which is [two Zeitgeist codebase upgrades down the line](https://github.com/zeitgeistpm/zeitgeist/issues/399). As soon as the Zeitgeist codebase is updated to `polkadot-v0.9.12`, all this additional computation is not necessary anymore, since the event will contain this information. When the runtime upgrade that contains the `polkadot-v0.9.12` codebase is executed, we have to ensure that we do not subtract the fee twice (once for every `ExtrinsicSuccess` or `ExtrinsicFailure` event and once for the `Withdraw` event.

**Comment by saboonikhil** [comment]
Update: After mapping `ExtrinsicSuccess` and `ExtrinsicFailure` events, it feels like the processor has slowed down a lot considering the number of such events and the **unavoidable** rpc calls that come along with each one of them. It is better if we cache few details within the framework of the subsquid so as to bring the processor back in form.

**Comment by saboonikhil** [comment]
Update: I have created a separate issue for caching of txn fee details to reduce latency in the processor while mapping indexed data. However, after including the transaction fee, the major discrepancies in the `Ztg` balances seem to have been solved and hence closing this issue.
