### ISSUE TITLE
Remove `Set-Cookie` on requests from stellate or in general.

### ISSUE THREAD

**Issue by yornaath** [zeitgeistpm/zeitgeist-subsquid#442]
The squid gql endpoint responds with a header that prevents stellate from implementing a cache.

- [ ] `Set-Cookie` header needs to be removed on response headers. _At least for requests coming from stellate._
<img width="912" alt="Screenshot 2023-10-11 at 11 49 37" src="https://github.com/zeitgeistpm/zeitgeist-subsquid/assets/411755/d7a80585-5c37-4180-89fd-ab73af1ad62b">

**Comment by saboonikhil** [comment]
That seem to be coming in from node balancer. Disabled it for stellate!
