### ISSUE TITLE
Market filter doesn't work on test.staging.zeitgeist.pm

### ISSUE THREAD

**Issue by maltekliemann** [zeitgeistpm/zeitgeist-subsquid#480]
<img width="1920" alt="Screenshot 2024-01-07 at 19 00 27" src="https://github.com/zeitgeistpm/ui/assets/49552287/9772d74d-66da-4bf4-a1b5-d43c8ece662c">

**Comment by Robiquet** [comment]
@saboonikhil think this is indexer related

**Comment by saboonikhil** [comment]
Related to migration to ArrowSquid. Fixed, thanks for bringing this up!
