### ISSUE TITLE
Duplicated `Withdrawn` event from `orml-tokens` and `orml-unknown-tokens`

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist-subsquid#496]
I noticed the `Withdrawn` event on `historicalAccountBalances`. There are two occurrences of an event named `Withdrawn`. One [here](https://github.com/open-web3-stack/open-runtime-module-library/blob/139c32f3522b4b3e603ad5cb9dca106e1afc9110/tokens/src/lib.rs#L318) and the other one [here](https://github.com/open-web3-stack/open-runtime-module-library/blob/139c32f3522b4b3e603ad5cb9dca106e1afc9110/unknown-tokens/src/lib.rs#L30). Now the question arises, which event of those both is emitted concretely?

I assume it's from `orml-tokens`, but I would expect to know this from the `extrinsic` field. However the extrinsic field is assigned to null.

```json
{
  "accountId": "dE1VdxVn8xy7HFNWfF1crL9zViS85kpPfphpt9NgnLdQXSMUd",
  "assetId": "{\"categoricalOutcome\":[59,2]}",
  "blockNumber": 1966744,
  "dBalance": "-38301310652",
  "event": "Withdrawn",
  "extrinsic": null,
  "id": "0001966744-acfb6-000028-XSMUd",
  "timestamp": "2022-12-26T02:42:18.356000Z"
},
```

Those ambiguous events should be distinctive using the extrinsic hash and name. Since we utilise `orml-unknown-tokens` in our protocol too, it could have also meant the event there.

**Comment by saboonikhil** [comment]
We're currently processing `Withdrawn` event from `Currency` and `Tokens` pallets only. You can find the list of events being processed [here](https://github.com/zeitgeistpm/zeitgeist-subsquid/blob/main/typegen.json).
