### ISSUE TITLE
Order book indexing

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#497]
- Add new `orders` schema to match on-chain data, in addition would be good to have order placed date and record partial fills
- Update `historicalSwaps` to index order fills
- Update `volume` and `liquidity` properties to account for orders

**Comment by saboonikhil** [comment]
I could see only `Orderbook.OrderPlaced` event on testnet.

![Screenshot 2024-02-20 at 8 35 53 PM](https://github.com/zeitgeistpm/zeitgeist-subsquid/assets/36529278/8b27411c-7f50-4c50-b066-3c7233b4f6dd)

**Comment by Robiquet** [comment]
You might need to fill orders via polkadot js

**Comment by saboonikhil** [comment]
> You might need to fill orders via polkadot js

Shouldn't these [events](https://github.com/zeitgeistpm/zeitgeist/blob/main/zrml/orderbook/src/lib.rs#L132-L148) help instead?

**Comment by saboonikhil** [comment]
3rd requirement should be accomplished indirectly when assets are spawned due to amm2 events (post implementation hybrid router).  And orderbook only markets will be non-existent (afaik).
