### ISSUE TITLE
Duplicated event for the same action `Transfer` and `AssetTxFeePaid`

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist-subsquid#498]
Look at this example on Zeitgeist mainnet:

```graphql
query MyQuery {
  historicalAccountBalances(
    limit: 100,
    orderBy: timestamp_ASC,
    where: {
      AND: [
        { extrinsic: { hash_eq: "0xdd7a74e735311827042cc5ed81d4d45aaf0c0e37777bdc85d1c865d04d03fd37"}}
      ]
    }
  ) {
    accountId
    assetId
    blockNumber
    dBalance
    event
    extrinsic {
      hash
      name
    }
    id
    timestamp
  }
}

```

It seems like we have a double booking of the same amount `3675826` for `AssetTxFeePaid` and for `Transfer`. Is this how it is supposed to be or is a change required?

I can live with that in my capital gain export, since it only means to cancel all `AssetTxFeePaid` events out and just use the `Transfer` events. Do you agree with my assumption above and with my consequent approach?

**Comment by Chralt98** [comment]
On the other hand this extrinsic "0x974138b045dfcaa2927e3b21dfb299e284358e92d7f1638754cd362de03104a5" doesn't have any transfer associated with it. So, I can't just assume that every `AssetTxFeePaid` event has a corresponding `Transfer` event...

**Comment by saboonikhil** [comment]
You've cracked the reason for deprecation of `historicalAccountBalances`, it currently stores two entries for a single transfer action: one for the sender and other for the receiver (wherever applicable).

I plan to create an entity `HistoricalTransfers` which has `from` and `to` fields on it.

**Comment by Chralt98** [comment]
> Do you know why this doesn't load [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmain.rpc.zeitgeist.pm%2Fws#/explorer/query/4221434)?

No, but you can load this https://zeitgeist.subscan.io/extrinsic/0x974138b045dfcaa2927e3b21dfb299e284358e92d7f1638754cd362de03104a5

**Comment by Chralt98** [comment]
> it currently stores two entries for a single transfer action: one for the sender and other for the receiver (wherever applicable).

I think this is fine. I can deal with this. I don't necessarily need a combined event. 

~~However, I just meant that `0xdd7a74e735311827042cc5ed81d4d45aaf0c0e37777bdc85d1c865d04d03fd37` indicates an event `AssetTxFeePaid` and `Transfer` with the same amount, why?~~

UPDATE: I think I made a mistake in looking it up. I thought that you would `Transfer` and `AssetTxFeePaid` would have emitted the same amount. But that is not the case... Thanks!

One for sender and one for receiver for one `Transfer` event is totally fine.
