### ISSUE TITLE
Computation of liquidity history

### ISSUE THREAD

**Issue by saboonikhil** [zeitgeistpm/zeitgeist-subsquid#501]
### This is how liquidity history looks like:

> Step 1: Liquidity of pool = `Price of asset` * `Amount of asset in pool`

An example [here](https://github.com/zeitgeistpm/zeitgeist-subsquid/blob/test/src/server-extension/query.ts#L78-L112) considers both old and new pool for liquidity computation.

> Step 2: Liquidity of pool vs Time  = `Price of asset` vs Time * `Amount of asset in pool` vs Time

`Price of asset` vs Time: can be computed using `HistoricalAsset` [[Example](https://github.com/zeitgeistpm/zeitgeist-subsquid/blob/test/src/server-extension/query.ts#L4-L32)]
`Amount of asset in pool` vs Time: can be computed using `HistoricalAccountBalance` [[Example](https://github.com/zeitgeistpm/zeitgeist-subsquid/blob/test/src/server-extension/query.ts#L34-L46)]

> Step3: Total Liquidity vs Time  = Sum of (`Price of asset` vs Time * `Amount of asset in pool` vs Time) for all pools

A final piece which stitches the above computations together and possibly emit a queryable endpoint for OKR metrics.

**Comment by Chralt98** [comment]
looks OK
