### ISSUE TITLE
`NeoSwaps.sell` `assetAmountOut` does not match the `dBalance` of the `Transfer` transaction

### ISSUE THREAD

**Issue by Chralt98** [zeitgeistpm/zeitgeist-subsquid#504]
Consider the following query:

```graphql
query MyQuery {
  txs: historicalAccountBalances(limit: 100, orderBy: timestamp_ASC, where: {
    extrinsic: { hash_eq: "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e" }
    accountId_eq: "dE17owFuqybtXatuqm4n4Qu1Gxjdatctj7SY224E19x86vQ7o",
  }) {
    accountId
    assetId
    dBalance
    blockNumber
    event
    extrinsic {
      hash
      name
    }
    id
    timestamp
  }
  swaps: historicalSwaps(limit: 10, orderBy: timestamp_ASC, where: {
    extrinsic: { hash_eq: "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e"},
  }) {
    accountId
    assetAmountIn
    assetAmountOut
    assetIn
    assetOut
    blockNumber
    event
    extrinsic {
      name
      hash
    }
    id
    timestamp
  }
}
```

I got the following json output:

```json
    "txs": [
      {
        "accountId": "dE17owFuqybtXatuqm4n4Qu1Gxjdatctj7SY224E19x86vQ7o",
        "assetId": "Ztg",
        "dBalance": "-245841498",
        "blockNumber": 4766465,
        "event": "Withdraw",
        "extrinsic": {
          "hash": "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e",
          "name": "NeoSwaps.sell"
        },
        "id": "0004766465-b9c00-000003-6vQ7o",
        "timestamp": "2024-01-25T19:53:48.547000Z"
      },
      {
        "accountId": "dE17owFuqybtXatuqm4n4Qu1Gxjdatctj7SY224E19x86vQ7o",
        "assetId": "{\"categoricalOutcome\":[359,0]}",
        "dBalance": "-7520187",
        "blockNumber": 4766465,
        "event": "Transfer",
        "extrinsic": {
          "hash": "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e",
          "name": "NeoSwaps.sell"
        },
        "id": "0004766465-b9c00-000005-6vQ7o",
        "timestamp": "2024-01-25T19:53:48.547000Z"
      },
      {
        "accountId": "dE17owFuqybtXatuqm4n4Qu1Gxjdatctj7SY224E19x86vQ7o",
        "assetId": "{\"categoricalOutcome\":[359,0]}",
        "dBalance": "-2352790000000",
        "blockNumber": 4766465,
        "event": "Transfer",
        "extrinsic": {
          "hash": "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e",
          "name": "NeoSwaps.sell"
        },
        "id": "0004766465-b9c00-000007-6vQ7o",
        "timestamp": "2024-01-25T19:53:48.547000Z"
      },
      {
        "accountId": "dE17owFuqybtXatuqm4n4Qu1Gxjdatctj7SY224E19x86vQ7o",
        "assetId": "{\"foreignAsset\":0}",
        "dBalance": "1536636475008",
        "blockNumber": 4766465,
        "event": "Transfer",
        "extrinsic": {
          "hash": "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e",
          "name": "NeoSwaps.sell"
        },
        "id": "0004766465-b9c00-000014-6vQ7o",
        "timestamp": "2024-01-25T19:53:48.547000Z"
      }
    ],
    "swaps": [
      {
        "accountId": "dE17owFuqybtXatuqm4n4Qu1Gxjdatctj7SY224E19x86vQ7o",
        "assetAmountIn": "2352790000000",
        "assetAmountOut": "1567996403069",
        "assetIn": "{\"categoricalOutcome\":[359,0]}",
        "assetOut": "{\"foreignAsset\":0}",
        "blockNumber": 4766465,
        "event": "SellExecuted",
        "extrinsic": {
          "name": "NeoSwaps.sell",
          "hash": "0x81a849e90fcb21dac2f59a866b92e2db9bd0a11f72d536a7d3feb902fbf5de9e"
        },
        "id": "0004766465-b9c00-000015",
        "timestamp": "2024-01-25T19:53:48.547000Z"
      }
    ],
```

The `assetAmountOut` of `1567996403069` does not match the respective `Transfer` transaction, which is of `dBalance` `1536636475008`. Where went the missing `1567996403069 - 1536636475008 = 31359928061` amount?

**Comment by Chralt98** [comment]
Additional question: What is the `7520187` `Transfer` amount telling us?

**Comment by Chralt98** [comment]
It seems like the AMM behaviour is explicitly represented in the transaction events. I weakly remember how neo-swaps works, but I guess it was like additionally buying (of amount `1567996403069 - 1536636475008 = 31359928061`) in this case with DOT a full set internally and selling all not wanted outcome assets to the pool to get the desired outcome asset (of amount `7520187`), which is sent to the pool. Is this correct?

**Comment by maltekliemann** [comment]
I admit the `SellExecuted` docs are slightly unclear on this, so I fixed them: https://github.com/zeitgeistpm/zeitgeist/pull/1250

The `amount_out` value is the amount leaving the pool, with swap fees and external fees not yet deducted. The missing `31_359_928_061` is exactly the value of the `swap_fee_amount` field, and there are no external fees.

**Comment by saboonikhil** [comment]
> The `amount_out` value is the amount leaving the pool, with swap fees and external fees not yet deducted. The missing `31_359_928_061` is exactly the value of the `swap_fee_amount` field, and there are no external fees.


When is the `swap_fee_amount` deducted? Which account gets this amount?

**Comment by Chralt98** [comment]
@maltekliemann Why there are no external fees charged? @saboonikhil Can we please extract the `swap_fee_amount` and `external_fee_amount` out of the neo-swap events?

**Comment by Chralt98** [comment]
@maltekliemann What is this amount `7520187`? Why does it go to the treasury [here](https://polkadot.js.org/apps/?rpc=wss%3A%2F%2Fmain.rpc.zeitgeist.pm%2Fws#/explorer/query/4766465)? When I hear treasury, I instantly think of fees. But why should the treasury ever receive outcome asset fees? In this case it is `categoricalOutcome[359, 0]`. This makes no sense atm to me.

**Comment by maltekliemann** [comment]
The account got dusted, hence the transfer to the treasury.

**Comment by maltekliemann** [comment]
> > The `amount_out` value is the amount leaving the pool, with swap fees and external fees not yet deducted. The missing `31_359_928_061` is exactly the value of the `swap_fee_amount` field, and there are no external fees.
> 
> When is the `swap_fee_amount` deducted? Which account gets this amount?

During the transaction. The pool account receives the fee, and LPs can then withdraw it. The pool account can be calculated from the pool ID in the same fashion as for the legacy pools.

**Comment by maltekliemann** [comment]
> @maltekliemann Why there are no external fees charged?

Because the pool has creator fees set to zero.
