### ISSUE TITLE
Querying outcomes / pool tokens for active markets

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist-subsquid#54]
Anyway, the issue is, Exchange component on the web app needs the collection of all pool tokens that can be traded with, those are tokens for markets that haven't ended yet (end timestamp is some future time).

the structure of tokens in such collection needs to be convertable for a type swap extrinsic expects for token.

If this is possible right now, I'd need some help with the graphql query syntax that can be used.

**Comment by saboonikhil** [comment]
This should be possible if we add `outcomeAssets` field to the market schema and process in the similar fashion as done in the sdk. Assets can then be extracted for the markets which haven't ended yet.

Do you also need to know about the availability of `poolShare` tokens?

**Comment by TvrtkoM** [comment]
Yes, that should work, good idea.
