### ISSUE TITLE
Processing data from local node

### ISSUE THREAD

**Issue by TvrtkoM** [zeitgeistpm/zeitgeist-subsquid#55]
Since subsquid integration into our frontend application has started and in future more and more e2e tests will be added gradually, processing data from subsquid indexer in combination with local node will be needed.
It is also convenient to have this possibility in case testnet gets inaccessible during development.

**Comment by saboonikhil** [comment]
@TvrtkoM Can you share the error you're getting?

**Comment by saboonikhil** [comment]
I am unable to successfully run the docker image of `indexer-gateway` in my system (_Apple Silicon M1_) due to a recognised `qemu` bug. Probably will have to switch to my old system to fix this.

Ref - https://github.com/docker/for-mac/issues/5123#issuecomment-784992589

**Comment by TvrtkoM** [comment]
I updated the code a bit and am able to run everything locally but there are few things for notice
- to run everything locally ipfs url for sdk needs to be configurable
- after I transfer some amount of ztg to my wallet account processor stops with an error, but this can be avoided by using `BLOCK_ZERO` environment variable to newest block hash - so the script for running environment would need to expose block hash as a parameter or something similar. This could be useful for other testing scenarios

**Comment by saboonikhil** [comment]
> I am unable to successfully run the docker image of `indexer-gateway` in my system (_Apple Silicon M1_) due to a recognised `qemu` bug. Probably will have to switch to my old system to fix this.
> 
> Ref - [docker/for-mac#5123 (comment)](https://github.com/docker/for-mac/issues/5123#issuecomment-784992589)

Workaround: https://docs.subsquid.io/recipes/how-to-launch-a-squid-archive#caveats-for-m1-macs
