### ISSUE TITLE
Market volume

### ISSUE THREAD

**Issue by Robiquet** [zeitgeistpm/zeitgeist-subsquid#69]
I would like to be able to do something like this so that we can show the most popular markets on the front end:
query MyQuery {
  markets(limit: 5, orderBy: volume_DESC, where: {status_eq: "Active"}) {
    img
    id
    description
    question
    outcomeAssets
  }
}

Where volume is the total amount of ZTG that has moved through a market's liquidity pool

**Comment by saboonikhil** [comment]
A new field `ztgQty` has been added to the pool schema connected to the market (via `marketId`). It reflects the total `Ztg` balance available in the pool account (via `accountId`) of the market.

```
query MyQuery {
  pools(orderBy: ztgQty_DESC) {
    marketId
    accountId
    ztgQty
  }
}
```

**Comment by Robiquet** [comment]
That's useful but not quite the metric that I'm looking for. I'm looking for the amount of ZTG that has passed through the pool not the total amount of ZTG inside of it. 

For example if I create a market with a pool with 100 of A, 100 of B and 100 ZTG and I buy 10 of A. The amount of ZTG in the pool would now be 90 but the pool volume would be 10. Hope that makes sense!
