### ISSUE TITLE
Add court events to be tracked and indexed by subsquid

### ISSUE THREAD

**Issue by lsaether** [zeitgeistpm/zeitgeist-subsquid#81]
Events being emitted from the court pallet need to be tracked and indexed

**Comment by saboonikhil** [comment]
Are the events available yet? @maltekliemann @sea212

**Comment by maltekliemann** [comment]
No, `court` isn't even implemented properly right now, so this will take a while.

**Comment by saboonikhil** [comment]
`Court` and `HistoricalCourt` schemas initialised capturing changes coming from court events.
